### ISSUE TITLE
Incorrect dot size 

### ISSUE THREAD

**Issue by ArmChilingarov** [tommybuonomo/dotsindicator#128]
UI bug when there are many dots , and the width of dots container is more than device width . try to  set 50 items in viewPager . 

Also Good to have a scrolling feature for large number of dots .  Now, it  just stacks on the  end dot.

![photo_2021-06-16 14 22 25](https://user-images.githubusercontent.com/28526900/122202628-49a34400-ceae-11eb-8702-bd110441eb6d.jpeg)
![photo_2021-06-16 14 22 27](https://user-images.githubusercontent.com/28526900/122202656-4e67f800-ceae-11eb-8c30-444d7d3b7439.jpeg)

version - 'com.tbuonomo:dotsindicator:4.2'

 <com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator
            android:id="@+id/diPagerDots"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            app:dotsColor="@color/white"
            app:dotsCornerRadius="6dp"
            app:dotsSize="12dp"
            app:dotsSpacing="6dp"
            app:dotsStrokeColor="@color/red"
            app:dotsStrokeWidth="2dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            />

**Comment by tommybuonomo** [comment]
Hello @ArmChilingarov 
Thanks for your contribution
In fact, this is because there is too much dots in your view. I don't really see the interest of having an infinite list of dots
In my opinion, dots are useful only when you have a finite number of pages (like into an on-boarding screen for instance)
I think you shouldn't use dots when there is too much pages
