### ISSUE TITLE
WormDotsIndicator - Wrong position [Android 9 api 28]

### ISSUE THREAD

**Issue by KohFujimura** [tommybuonomo/dotsindicator#50]
Steps to reproduce:

Viewpaper + WormDotsIndicator
- Swipe to the last item
- Swipe back to the first item
=> always show the second dot instead of the first dot.

**Comment by tommybuonomo** [comment]
Hi @KohFujimura,
How many items do you have in your case? I can't reproduce the bug.
Thanks

**Comment by KohFujimura** [comment]
https://drive.google.com/file/d/1lfFzBSNEXKPgqgdLwGZWQJZ8Kr5zddLp/view?usp=sharing

a video for more details :)

**Comment by tommybuonomo** [comment]
@KohFujimura Can you please try with the last version `4.0` ?

**Comment by KohFujimura** [comment]
i just switch to 4.0 and run the project :
i got this thing https://imge.to/i/vU4FkZ

**Comment by tommybuonomo** [comment]
@KohFujimura what's about the last version `4.1.1` ?

**Comment by Nevercom** [comment]
I've faced this too. In my case, the problem is because of `ViewPager.setPageMargin()` method.
Whenever i comment that line, everything works fine. but if i set a PageMargin on ViewPager, when i go back to the first fragment, Indicator shows that it's the second.

I'm using the latest `4.1.2` version of the library.

**Comment by romitarora** [comment]
Thank you so much, @Nevercom .... **ViewPager.setPageMargin()** this is the only issue, i remove it and everything is working fine now. but what to do if i need some margin to viewpager?

**Comment by egek92** [comment]
ViewPager.setPageMargin() causes wrong positioning
